# this is an example on how to setup CI to generate CC and upload to codeclimate
name: CI

on:
  push:
  schedule:
  - cron: "0 0 * * *"

jobs:
  cc:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Checkout master
      run: git checkout master
    - name: Run the tests with coverage using lcov
      working-directory: ./lib
      run: |
        pm install
        npm run test:coverage
    - name: Generate formatted coverage for codeclimate
      working-directory: ./lib
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x cc-test-reporter
        ./cc-test-reporter format-coverage -t lcov
    - name: Upload coverage report to codeclimate
      working-directory: ./lib
      env:
       CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        ./cc-test-reporter upload-coverage
