name: tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run all unit tests
      working-directory: ./lib
      run: |
        npm install
        npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check for linting
      working-directory: ./lib
      run: |
        npm install
        npm run lint

